Tugas1Setup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import add_friends.urls as add_friends
import halaman_profile.urls as halaman_profile
import update_status.urls as update_status
import fitur4.urls as fitur4
from django.views.generic.base import RedirectView
#from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^add_friends/', include(add_friends,namespace='add_friends')),
    url(r'^halaman_profile/', include(halaman_profile,namespace='halaman_profile')),
    url(r'^update_status/', include(update_status,namespace='update_status')),
	url(r'^fitur4/', include(fitur4,namespace='fitur4')),
	url(r'^$', RedirectView.as_view(permanent = True, url = '/update_status/'), name='index')
]

add_friends/urls.py
from django.conf.urls import url
from .views import index, add_friends

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friends', add_friends, name='add_friends')
]

fitur4/urls.py
from django.conf.urls import url
from .views import index

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

halaman_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_status, remove_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^remove_status', remove_status, name='remove_status'),
]

add_friends/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    name = models.CharField(max_length=27)
    heroku_url = models.TextField(max_length=200)
    created_date = models.DateTimeField(auto_now_add=True)

fitur4/models.py
from django.db import models

# Create your models here.

halaman_profile/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
	name = models.CharField(max_length=32)
	birth_date = models.CharField(max_length=6)
	gender = models.CharField(max_length=6)
	expertise = models.TextField(max_length=150)
	description = models.CharField(max_length=200)
	email = models.CharField(max_length=100)

update_status/models.py
from django.db import models

class Status(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

add_friends/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
    	'required': 'Tolong isi input ini',
    	'invalid': 'Isi input dengan url'
    }
    name_attrs = {
        'type': 'text',
        'class': 'todo-form-name',
        'placeholder':'Masukkan nama...'
    }
    heroku_url_attrs = {
        'type': 'text',
        'class': 'todo-form-heroku_url',
        'placeholder':'Masukkan heroku url...'
    }
    name = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=name_attrs))
    heroku_url = forms.URLField(label='', required=True, max_length=200, widget=forms.TextInput(attrs=heroku_url_attrs))

update_status/forms.py
from django import forms


class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder': 'Your Status...'
    }

    description = forms.CharField(
        label='', required=True, widget=forms.Textarea(attrs=description_attrs))

add_friends/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Todo_Form
from .models import Post

# Create your views here.
response = {'author': "Kelompok 2 - PPW B"}

def index(request):
    response['Todo_form'] = Todo_Form
    post = Post.objects.all()
    response['post'] = post
    html = 'add_friends/add_friends.html'
    return render(request, html, response)

def add_friends(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['heroku_url'] = request.POST['heroku_url']
        post = Post(name=response['name'],heroku_url=response['heroku_url'])
        post.save()
        return HttpResponseRedirect('/add_friends/')
    else :
        return HttpResponseRedirect('/add_friends/')

fitur4/views.py
from django.shortcuts import render
from update_status.models import Status
from add_friends.models import Post
from halaman_profile.models import Profile


# Create your views here.
def index(request):
	totalstatus = Status.objects.count();
	totalfriend = Post.objects.count();
	#name = Profile.object.name();
	lastpost = Status.objects.last();

	response = {'name' : "Kelompok 02", 'totalstatus':totalstatus, 'totalfriend':totalfriend, 'lastpost':lastpost}
	return render(request,'fitur4/stathtml.html',response)

halaman_profile/views.py
from django.shortcuts import render
from .models import Profile

# Create your views here.
name ="Kelompok 02"
birth_date = "03 Okt"
gender = "Male"
description = "Impossible it's Nothing. Your Future Programmer"
email = "Kelompok02PPW@gmail.com"
expertise = ["Programmer","Hardworker","Students"]

Profile = Profile(name=name, birth_date=birth_date, gender=gender, description=description, email=email, expertise=expertise)

def index(request):
	response = {'Nama': Profile.name,'Birthday': Profile.birth_date, 'Gender': Profile.gender, 'Expertise': Profile.expertise, 'Description': Profile.description, 'Email': Profile.email}
	html = 'halaman_profile/halaman_profile.html'
	return render(request,html,response)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status

# Create your views here.
response = {}
def index(request):    
    response['author'] = "Nathanael Lemuella" #TODO Implement yourname
    status = Status.objects.all()
    response['status'] = status
    html = 'update_status/update_status.html'
    response['status_form'] = Status_Form
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        status = Status(description=response['description'])
        status.save()
        return HttpResponseRedirect('/update_status/')
    else:
        return HttpResponseRedirect('/update_status/')

def remove_status(request):
    try:
        idObjek = request.POST['flag']
        Status.objects.filter(id=idObjek).delete()
    except ValueError or KeyError:
        pass
    return HttpResponseRedirect('/update_status/')

add_friends/templates/add_friends/add_friends.html
{% extends "add_friends/layout/base.html" %}

{% block content %}
<style>
    body {
    margin-top: 70px;
    
}
/* Textarea not resizeable */
textarea {
    resize:none
}
section{
    min-height: 600px;
}
/* styling footer */
footer p {
    text-align: center;
    padding-top: 10px;
}

  /* styling form */
#form form{
    width: 400px;
    margin: 50px auto;
    text-align: center;
    position: relative;
    z-index: 1;
    background: white;
    border: 0 none;
    border-radius: 3px;
    box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.4);
    padding: 20px 30px;
    box-sizing: border-box;
    position: relative;
}
  /* styling judul form, apakah arti dari tanda '>' ? */
#form form > h2{
    font-size: 1.3em;
    text-transform: uppercase;
    color: #2C3E50;
    margin-bottom: 10px;
}
#form form > .todo-form-name, #form form > .todo-form-heroku_url{
    padding: 15px;
    border: 1px solid #ccc;
    border-radius: 3px;
    margin-bottom: 10px;
    width: 100%;
    box-sizing: border-box;
    color: #2C3E50;
    font-size: 13px;
}
table tr:nth-child(odd){
    text-align: center;
    color:  #4f6457;
    padding: 5px;
    font-size: 12px;
    background: #75b1a9;
    font-weight: bold;
}
table tr:nth-child(even){
    text-align: center;
    color: #4f6457;
    padding: 5px;
    font-size: 12px;
    background: #acd0c0;
    font-weight: bold;
}
h1 {
    text-align: center;
    margin: 10px;
}

</style>
    <section name="form" id="form">
        <form id="form" method="POST" action="{% url 'add_friends:add_friends' %}">
            <h2>Add Friends</h2>
            {% csrf_token %}
            {{ Todo_form }}
            <br>
            <button type="submit" class="btn btn-default">Add</button>
        </form>
    </section>

    <section name ="friend" id="friends">
        <h1>List Friend</h1>
        <table class="table">
            <tbody>
                {% for i in post %}
                <tr>
                    <td> {{i.name}} </td>
                    <td><a href= {{i.heroku_url}}> {{i.heroku_url}}</a> </td>
                    <td> Added {{i.created_date}} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}

    
    

add_friends/templates/add_friends/layout/base.html
<!-- {% load staticfiles %} -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="PROFILE">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    

    <title> 
        {% block title %} Profile {{author}}{% endblock %}
    </title>
</head>

<body style="background: lightcyan">
    <header>
        {% include "add_friends/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>
    </content>
    <footer style="margin-top: 100px">
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "add_friends/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

add_friends/templates/add_friends/partials/footer.html
<p style="text-align: center;">Made by PPW B - Kelompok 2</p>

add_friends/templates/add_friends/partials/header.html
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar" aria-expanded="false" aria-controls="navbar"">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>                        
			</button>
		</div>
	<ul class="nav navbar-nav navbar-right">
		<li><a href="/update_status/">Status</a></li>
		<li><a href="/halaman_profile/">Profil</a></li>
		<li><a href="/add_friends/">Friends</a></li>
		<li><a href="/fitur4/">Stats</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-left">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Ling In</a></li>
	</ul>
</nav>

fitur4/templates/fitur4/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="STATISTIC">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    

    <title> 
        {% block title %} Statistic {{author}}{% endblock %}
    </title>
</head>

<body>
    <header>
	{% include "fitur4/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
		{% include "fitur4/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

fitur4/templates/fitur4/stathtml.html
{% extends "fitur4/layout/base.html" %}

{% block content %}

{% load staticfiles %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/statistic.css' %}" 
<div class="container">
<img src="https://cdn4.iconfinder.com/data/icons/people-14/24/Anonymous-2-512.png" style="width: 200px; height: 200px; border-radius: 100%;" margin-top = 100px>
<h1 style="text-align: left;">{{ name }}</h1>

<div class="col-sm-6" >
	<span class="glyphicon glyphicon-list" aria-hidden="true"></span>
	Posts : {{ totalstatus }}
</div>
<div class="col-sm-6" >
	<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
	Friends : {{ totalfriend }}
</div>
<div class="" style="padding: 30px;font-size: 25px;">
	Latest Post<br>
	{% if lastpost %}
	<img src=""https://cdn4.iconfinder.com/data/icons/people-14/24/Anonymous-2-512.png" style="width: 150px; height: 150px; border-radius: 100%;">
	{{ name }} <br>
	{{ lastpost.status }}<br>
	{{ lastpost.created_date }}
	{% else %}
	<p>No Posts!</p>
	{% endif %}
</div>
{% endblock %}

halaman_profile/templates/halaman_profile/halaman_profile.html
		{% extends "halaman_profile/layout/base.html" %}

		{% block content %}
		<style>
			.Nama{
				
			}

			.button {
			background-color: #cbd1c8;
			border: none;
			color: black;
			padding: 5px 15px;
			text-align: center;
			text-decoration: none;
			display: inline-block;
			margin: 4px 2px;
			cursor: pointer;
			}
			.button1 {border-radius: 12px;}

			@media only screen and (max-width: 480px) {
				#input-list form {
				width: 290px;
				}
				.to-do-list .to-do-list-delete {
				bottom: -50px;
				}
				.flex-item{
				padding: 0 15px;
				flex-grow: 0;
				flex-shrink: 0;
				flex-basis: 100%;
				}
			}
			body{
			  margin-top: 70px;
			  background-image: url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTt1JT4a5DvOj11378D0BUdOFYmFbXq5G6GBplc3GZCj37K_m9B);
			  background-size: cover;
			  background-repeat: no-repeat;
			}

			/* Custom navbar style */
			.navbar-static-top {
			  margin-bottom: 19px;
			}
			.navbar-default .navbar-nav>li>a {
			    cursor: pointer;
			}

			/* Textarea not resizeable */
			textarea {
			    resize:none
			}
			section{
			  min-height: 600px;
			}
			/* animasi pada title */
			.main-title{
			  -webkit-animation: colorchange 1s infinite;
			  -webkit-animation-direction: alternate;
			  text-align: center;
			}

			/* animasi colorchange */
			@-webkit-keyframes colorchange {
			    0% {
			        -webkit-text-stroke: 5px #0fb8ad;
			    letter-spacing: 0;
			    }
			  50% {
			    -webkit-text-stroke: 7.5px  #1fc8db;
			  }
			    100% {
			        -webkit-text-stroke: 10px  #2cb5e8;
			    letter-spacing: 18px;
			    }
			}
			/* styling footer */
			footer p{
				background: lightgrey;
				text-align: center;
				padding-top: 10px;
			}
			/* styling responsive max-width menandakan bahwa rule css ini hanya akan bekerja untuk layar dengan maksimal 768px, jika lebih dari 768px maka rule ini diabaikan */
			@media only screen and (max-width: 768px) {
			  #input-list form {
			      width: 290px;
			  }
			  .to-do-list .to-do-list-delete {
			    bottom: -50px;
			  }
			  .flex-item{
			    padding: 0 15px;
			    flex-grow: 0;
			    flex-shrink: 0;
			    flex-basis: 100%;
			  }
			}
		}
		</style>

		<section name="profile">
		<div class="container">
		    <h3 style="padding: 35px; text-align: left">Profile</h3>
		    <center>
		    	<img class="img-circle" src="https://cdn4.iconfinder.com/data/icons/people-14/24/Anonymous-2-512.png" style="width: 150px; height: 150px; border-radius: 100%;">
		    </center>
		    
		    <center>
		        <h2>
		            <font face="verdana">{{Nama}}</font>
		        </h2>
		    </center>
		    <hr/>
		    <div class = "col-md-4">
		    </div>
		    <div class="col-md-1">
		        <p> Birthday </p>
		        <p> Gender </p>
		        <p style="padding-top: 12px;padding-bottom: 6px"> Expertise </p>
		        <p> Description </p>
		        <p> Email </p>
		    </div>
		    <div class="col-md-7">
		        <p> {{Birthday}} </p>
		        <p> {{Gender}} </p>
		        <p> {% for ii in Expertise %}
		                <button class='button button1'>{{ ii }}</button>
		            {% endfor %}
		        <p> {{Description}} </p>
		        <p> {{Email}} </p>
		    </div>
		</div>
		</section>
		{% endblock %}

halaman_profile/templates/halaman_profile/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="PROFILE">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    

    <title> 
        {% block title %} Profile {{author}}{% endblock %}
    </title>
</head>

<body style="background-image: url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTt1JT4a5DvOj11378D0BUdOFYmFbXq5G6GBplc3GZCj37K_m9B);">
    <header>
        {% include "halaman_profile/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "halaman_profile/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<style>

</style>
<html lang="en">
<head>
	<title>Tugas 1 PPW</title>
	 <title>Bootstrap Example</title>
	 <meta charset="utf-8">
	 <meta name="viewport" content="width=device-width, initial-scale=1">
	 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<style>
		footer {
			background-color: #555;
			color: white;
			padding: 5px;
		
			}
	</style>
</head>
<body>
	<header>
		{% include "partials/header.html" %}
	</header>
	<content style="min-height: 85vh">
		{% block content %}
		<!-- content goes here -->
		{% endblock %}
	</content>
	<footer>
		{% block footer %}
		{% include "partials/footer.html" %}
		{% endblock %}
	</footer>

	<!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

update_status/templates/update_status/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Update Status">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />
    <title>
        {% block title %} Update Status By {{author}} {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "update_status/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "update_status/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

update_status/templates/update_status/partials/footer.html
<!-- templates/update_status/partials/footer.html -->
<p> &copy; Made with Love by {{author}}</p>

update_status/templates/update_status/partials/header.html
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar aria-expanded="false" aria-controls="navbar"">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
      </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><a href="/update_status/">Status</a></li>
      <li><a href="/halaman_profile/">Profil</a></li>
      <li><a href="/add_friends/">Friends</a></li>
      <li><a href="/fitur4/">Stats</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-left">
          <li><a href="#"><span class="glyphicon glyphicon-user"></span> Ling In</a></li>
    </ul>
  </nav>